server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MoonMinHyuk1/spring-study.git
          search-paths: msa-practice/config
          default-label: master

#RabbitMQ
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, busrefresh