server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MoonMinHyuk1/spring-study.git
          search-paths: msa-practice/config
          default-label: master