name: Java CI with Gradle

on:
  push: #해당 브랜치에 push 했을 때
    branches:
      - master
  pull_request: #해당 브랜치에 pr 날렸을 때
    branches:
      - master

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      #jdk 세팅
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      #github-actions-secret properties
      #    - name: make application-test.properties
      #      run: |
      #        cd ./src/test/resources
      #        touch ./application.properties
      #        echo "${{ secrets.PROPERTIES_TEST }}" > ./application-test.properties
      #      shell: bash

      - name: Start MySQL
        uses: samin/mysql-action@v1.3
        with:
          host port: 3305
          container port: 3305
          mysql database: 'study'
          mysql user: 'user'
          mysql password: 'user'

      - name: Build with Test
        run: ./gradlew test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          files: build/test-results/**/*.xml