name: CI/CD

on:
  push: #해당 브랜치에 push 했을 때
    branches:
      - master
      - main
      - dev
  pull_request: #해당 브랜치에 pr 날렸을 때
    branches:
      - master
      - main
      - dev

permissions: write-all #테스트 결과 작성을 위해 쓰기권한 추가

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #jdk 세팅
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      #gradle 캐싱
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      ### CI
      #gradlew 쓰기 권한 추가
      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      #test를 제외한 코드 빌드
      - name: Build With Gradle
        run: ./gradlew build -x test

      #properties 설정
      #    - name: make application-test.properties
      #      run: |
      #        cd ./src/test/resources
      #        touch ./application.properties
      #        echo "${{ secrets.PROPERTIES_TEST }}" > ./application-test.properties
      #      shell: bash

      #test를 위한 mysql설정
      - name: Start MySQL
        uses: samin/mysql-action@v1.3
        with:
          host port: 3305
          container port: 3305
          mysql database: 'study'
          mysql user: 'user'
          mysql password: 'user'

      #test코드 빌드
      - name: Build With Test
        run: ./gradlew test

      #테스트 결과 파일 생성
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          files: build/test-results/**/*.xml

      ### CD
      #배포를 위한 prod properties 설정
      - name: Make application-prod.properties
        if: contains(github.ref, 'master')
        run: |
          cd ./src/main/resources
          touch ./application-prod.properties
          echo "${{ secrets.PROPERTIES_PROD }}" > ./application-prod.properties
        shell: bash

      #test를 제외한 코드 빌드 (생략 고민)
      - name: Build With Gradle
        if: contains(github.ref, 'master')
        run: ./gradlew build -x test

#      #도커 빌드 & 이미지 push
#      - name: Docker build & push to prod
#        if: contains(github.ref, 'master')
#        run: |
#          docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PASSWORD }}
#          docker build -f Dockerfile -t ${{ secrets.DOCKER_HUB_ID }}/pickrap .
#          docker push ${{ secrets.DOCKER_HUB_ID }}/pickrap


      #            git checkout dev
      #            git pull origin dev
      #            cd spring-study
      #docker-compose 파일을 ec2 서버에 배포 #docker-compose -f docker-ec2-test/docker-compose.yml up -d
      - name: Deploy to Prod
        uses: appleboy/ssh-action@master
        id: deploy-prod
        if: contains(github.ref, 'master')
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            sudo docker rm -f $(docker ps -qa)
            docker-compose -f spring-study/docker-compose.yml up -d
            docker image prune -f